---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.18

platforms:
  - name: centos-7.1
    driver:
      network:
      - ["forwarded_port", {guest: 4444, host: 4444}]
      - ["forwarded_port", {guest: 8910, host: 8910}]
  - name: ubuntu-14.04
    driver:
      network:
      - ["forwarded_port", {guest: 4444, host: 4445}]
      - ["forwarded_port", {guest: 8910, host: 8911}]
  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2
      network:
      - ["forwarded_port", {guest: 4444, host: 4446}]
      - ["forwarded_port", {guest: 8910, host: 8912}]

suites:
  - name: default
    run_list:
      - recipe[ghostdriver_test::package]
      - recipe[ghostdriver_test::java]
      - recipe[ghostdriver_test::hub]
      - recipe[ghostdriver_test::phantomjs_selenium]
      - recipe[ghostdriver_test::phantomjs_standalone]
    attributes:
      java:
        jdk_version: '7'
        windows:
          # TODO: REPLACE URL WITH ENVIRONMENT VARIABLE
          url: https://s3.amazonaws.com/prsnpublic/jdk-8u51-windows-i586.exe
      selenium:
        windows:
          java: C:\\Program Files (x86)\\Java\\jdk1.8.0_51\\bin\\java.exe
